import builtins as _b
from collections.abc import Iterator, Sequence
from contextlib import AbstractContextManager
from types import EllipsisType
from typing import Literal, SupportsIndex, Generic, overload, Protocol
from typing_extensions import TypeVar
from .. import Array as _NativeArray
import numpy as np
Scalar = np.bool_ | np.uint8 | np.uint16 | np.uint32 | np.uint64 | np.int8 | np.int16 | np.int32 | np.int64 | np.float32 | np.float64 | np.complex64 | np.complex128
_NDArray = np.ndarray[tuple[int, ...], np.dtype[Scalar]]
_DTypeLike = str | type[Scalar] | np.dtype[Scalar]

class _ArrayInput(Protocol):
    @property
    def dtype(self) -> np.dtype[Scalar]: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    def __array_namespace__(self, *, api_version: str | None = ...) -> _Namespace: ...

from ._policy import StorageWideningWarning as StorageWideningWarning, StorageWideningError as StorageWideningError, set_strict as set_strict, strict as strict

_DType = TypeVar("_DType", bound=Scalar, default=Scalar)

_Unsigned = TypeVar("_Unsigned", np.uint8, np.uint16, np.uint32, np.uint64)
_Signed = TypeVar("_Signed", np.bool_, np.int8, np.int16, np.int32, np.int64)
_Inexact = TypeVar("_Inexact", np.float32, np.float64, np.complex64, np.complex128)

_OtherDType = TypeVar("_OtherDType", bound=Scalar)

_Scalar = _b.bool | int | float | complex
_Shape = int | tuple[int, ...]
_Axis = int | tuple[int, ...] | None
_IndexItem = SupportsIndex | slice | EllipsisType | None | _ArrayInput | _NDArray
_Index = _IndexItem | tuple[_IndexItem, ...]
_Device = Literal['cpu'] | None
__array_api_version__: str
__version__: str
e: float
pi: float
inf: float
nan: float
newaxis: None
from numpy import bool as bool
from numpy import uint8 as uint8
from numpy import uint16 as uint16
from numpy import uint32 as uint32
from numpy import uint64 as uint64
from numpy import int8 as int8
from numpy import int16 as int16
from numpy import int32 as int32
from numpy import int64 as int64
from numpy import float32 as float32
from numpy import float64 as float64
from numpy import complex64 as complex64
from numpy import complex128 as complex128

class Array(Generic[_DType]):
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def dtype(self) -> np.dtype[_DType]: ...
    @property
    def device(self) -> Literal['cpu']: ...
    @property
    def storage_bits(self) -> int: ...
    @property
    def storage_nbytes(self) -> int: ...
    @property
    def T(self) -> Array[_DType]: ...
    @property
    def mT(self) -> Array[_DType]: ...
    def __getitem__(self, key: _Index, /) -> Array[_DType]: ...
    def __setitem__(self, key: _Index, value: _ArrayInput | _Scalar | Sequence[object] | _NDArray, /) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Array[_DType]]: ...
    @overload
    def __array__(self, dtype: None = ..., copy: _b.bool | None = ...) -> np.ndarray[tuple[int, ...], np.dtype[_DType]]: ...
    @overload
    def __array__(self, dtype: type[_OtherDType] | np.dtype[_OtherDType], copy: _b.bool | None = ...) -> np.ndarray[tuple[int, ...], np.dtype[_OtherDType]]: ...
    @overload
    def __array__(self, dtype: _DTypeLike | None = ..., copy: _b.bool | None = ...) -> _NDArray: ...
    def __array_namespace__(self, *, api_version: str | None = ...) -> _Namespace: ...
    def to_device(self, device: _Device, /, *, stream: None = ...) -> Array[_DType]: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(self, *, stream: None = ..., max_version: tuple[int, int] | None = ..., dl_device: tuple[int, int] | None = ..., copy: _b.bool | None = ...) -> object: ...
    def __bool__(self) -> _b.bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __add__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __radd__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __iadd__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __sub__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rsub__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __isub__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __mul__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rmul__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __imul__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __truediv__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rtruediv__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __itruediv__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __floordiv__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rfloordiv__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __ifloordiv__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __mod__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rmod__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __imod__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __pow__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rpow__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __ipow__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __matmul__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rmatmul__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __imatmul__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __and__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rand__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __iand__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __or__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __ror__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __ior__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __xor__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rxor__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __ixor__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __lshift__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rlshift__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __ilshift__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __rshift__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __rrshift__(self, other: _ArrayInput | _Scalar) -> Array[Scalar]: ...
    def __irshift__(self, other: _ArrayInput | _Scalar) -> Array[_DType]: ...
    def __eq__(self, other: _ArrayInput | _Scalar) -> Array[np.bool_]: ...  # type: ignore[override]
    def __ne__(self, other: _ArrayInput | _Scalar) -> Array[np.bool_]: ...  # type: ignore[override]
    def __lt__(self, other: _ArrayInput | _Scalar) -> Array[np.bool_]: ...
    def __le__(self, other: _ArrayInput | _Scalar) -> Array[np.bool_]: ...
    def __gt__(self, other: _ArrayInput | _Scalar) -> Array[np.bool_]: ...
    def __ge__(self, other: _ArrayInput | _Scalar) -> Array[np.bool_]: ...
    def __neg__(self) -> Array[Scalar]: ...
    def __pos__(self) -> Array[Scalar]: ...
    def __abs__(self) -> Array[Scalar]: ...
    def __invert__(self) -> Array[Scalar]: ...

@overload
def asarray(obj: object, /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ..., copy: _b.bool | None = ...) -> Array[np.bool_]: ...
@overload
def asarray(obj: object, /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ..., copy: _b.bool | None = ...) -> Array[_DType]: ...
@overload
def asarray(obj: Array[_DType] | np.ndarray[tuple[int, ...], np.dtype[_DType]], /, *, dtype: None = ..., device: _Device = ..., copy: _b.bool | None = ...) -> Array[_DType]: ...
@overload
def asarray(obj: _NativeArray, /, *, dtype: None = ..., device: _Device = ..., copy: _b.bool | None = ...) -> Array[np.uint8]: ...
@overload
def asarray(obj: object, /, *, dtype: str | None = ..., device: _Device = ..., copy: _b.bool | None = ...) -> Array[Scalar]: ...
@overload
def astype(x: _ArrayInput, dtype: type[np.bool_] | np.dtype[np.bool_], /, *, copy: _b.bool = ..., device: _Device = ...) -> Array[np.bool_]: ...
@overload
def astype(x: _ArrayInput, dtype: type[_DType] | np.dtype[_DType], /, *, copy: _b.bool = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def astype(x: _ArrayInput, dtype: str, /, *, copy: _b.bool = ..., device: _Device = ...) -> Array[Scalar]: ...
def reshape(x: Array[_DType], /, shape: tuple[int, ...], *, copy: _b.bool | None = ...) -> Array[_DType]: ...
def permute_dims(x: Array[_DType], /, axes: tuple[int, ...]) -> Array[_DType]: ...
def from_dlpack(x: object, /, *, device: _Device = ..., copy: _b.bool | None = ...) -> Array[Scalar]: ...
def broadcast_arrays(*arrays: _ArrayInput) -> tuple[Array[Scalar], ...]: ...
def meshgrid(*arrays: _ArrayInput, indexing: Literal['xy', 'ij'] = ...) -> tuple[Array[Scalar], ...]: ...
def broadcast_shapes(*shapes: tuple[int, ...]) -> tuple[int, ...]: ...
def can_cast(from_: _ArrayInput | _DTypeLike, to: _DTypeLike) -> _b.bool: ...
def isdtype(dtype: _DTypeLike, kind: object) -> _b.bool: ...
def result_type(*arrays_and_dtypes: _ArrayInput | _DTypeLike) -> np.dtype[Scalar]: ...
def abs(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def acos(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def acosh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def asin(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def asinh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def atan(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def atanh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def bitwise_invert(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def ceil(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def conj(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def cos(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def cosh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def exp(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def expm1(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def floor(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def imag(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def isfinite(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def isinf(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def isnan(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def log(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def log1p(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def log2(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def log10(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def logical_not(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def negative(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def positive(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def real(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def round(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def sign(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def signbit(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def sin(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def sinh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def sqrt(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def square(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def tan(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def tanh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def trunc(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def reciprocal(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def add(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def atan2(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def bitwise_and(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def bitwise_left_shift(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def bitwise_or(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def bitwise_right_shift(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def bitwise_xor(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def copysign(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def divide(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def equal(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def floor_divide(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def greater(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def greater_equal(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def hypot(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def less(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def less_equal(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def logaddexp(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def logical_and(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def logical_or(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def logical_xor(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def matmul(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def maximum(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def minimum(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def multiply(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def not_equal(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
def pow(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def remainder(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def subtract(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def nextafter(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
@overload
def sum(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: type[np.bool_] | np.dtype[np.bool_], keepdims: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def sum(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: type[_DType] | np.dtype[_DType], keepdims: _b.bool = ...) -> Array[_DType]: ...
@overload
def sum(x: Array[_Unsigned], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[np.uint64]: ...
@overload
def sum(x: Array[_Signed], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[np.int64]: ...
@overload
def sum(x: Array[_Inexact], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[_Inexact]: ...
@overload
def sum(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: str | None = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
@overload
def prod(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: type[np.bool_] | np.dtype[np.bool_], keepdims: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def prod(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: type[_DType] | np.dtype[_DType], keepdims: _b.bool = ...) -> Array[_DType]: ...
@overload
def prod(x: Array[_Unsigned], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[np.uint64]: ...
@overload
def prod(x: Array[_Signed], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[np.int64]: ...
@overload
def prod(x: Array[_Inexact], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[_Inexact]: ...
@overload
def prod(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: str | None = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
@overload
def cumulative_sum(x: _ArrayInput, /, *, axis: int | None = ..., dtype: type[np.bool_] | np.dtype[np.bool_], include_initial: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def cumulative_sum(x: _ArrayInput, /, *, axis: int | None = ..., dtype: type[_DType] | np.dtype[_DType], include_initial: _b.bool = ...) -> Array[_DType]: ...
@overload
def cumulative_sum(x: Array[_Unsigned], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[np.uint64]: ...
@overload
def cumulative_sum(x: Array[_Signed], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[np.int64]: ...
@overload
def cumulative_sum(x: Array[_Inexact], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[_Inexact]: ...
@overload
def cumulative_sum(x: _ArrayInput, /, *, axis: int | None = ..., dtype: str | None = ..., include_initial: _b.bool = ...) -> Array[Scalar]: ...
@overload
def cumulative_prod(x: _ArrayInput, /, *, axis: int | None = ..., dtype: type[np.bool_] | np.dtype[np.bool_], include_initial: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def cumulative_prod(x: _ArrayInput, /, *, axis: int | None = ..., dtype: type[_DType] | np.dtype[_DType], include_initial: _b.bool = ...) -> Array[_DType]: ...
@overload
def cumulative_prod(x: Array[_Unsigned], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[np.uint64]: ...
@overload
def cumulative_prod(x: Array[_Signed], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[np.int64]: ...
@overload
def cumulative_prod(x: Array[_Inexact], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[_Inexact]: ...
@overload
def cumulative_prod(x: _ArrayInput, /, *, axis: int | None = ..., dtype: str | None = ..., include_initial: _b.bool = ...) -> Array[Scalar]: ...
def mean(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
def std(x: _ArrayInput, /, *, axis: _Axis = ..., correction: float = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
def var(x: _ArrayInput, /, *, axis: _Axis = ..., correction: float = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
def max(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
def min(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
def all(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[np.bool_]: ...
def any(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[np.bool_]: ...
def count_nonzero(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[np.intp]: ...
def argmax(x: _ArrayInput, /, *, axis: int | None = ..., keepdims: _b.bool = ...) -> Array[np.intp]: ...
def argmin(x: _ArrayInput, /, *, axis: int | None = ..., keepdims: _b.bool = ...) -> Array[np.intp]: ...
@overload
def empty(shape: _Shape, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def empty(shape: _Shape, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def empty(shape: _Shape, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
@overload
def empty_like(x: _ArrayInput, /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def empty_like(x: _ArrayInput, /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def empty_like(x: Array[_DType], /, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def empty_like(x: _ArrayInput, /, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
@overload
def ones(shape: _Shape, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def ones(shape: _Shape, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def ones(shape: _Shape, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
@overload
def ones_like(x: _ArrayInput, /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def ones_like(x: _ArrayInput, /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def ones_like(x: Array[_DType], /, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def ones_like(x: _ArrayInput, /, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
@overload
def zeros(shape: _Shape, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def zeros(shape: _Shape, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def zeros(shape: _Shape, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
@overload
def zeros_like(x: _ArrayInput, /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def zeros_like(x: _ArrayInput, /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def zeros_like(x: Array[_DType], /, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def zeros_like(x: _ArrayInput, /, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
@overload
def full(shape: _Shape, fill_value: _Scalar, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def full(shape: _Shape, fill_value: _Scalar, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def full(shape: _Shape, fill_value: _Scalar, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
@overload
def full_like(x: _ArrayInput, fill_value: _Scalar, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def full_like(x: _ArrayInput, fill_value: _Scalar, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def full_like(x: Array[_DType], fill_value: _Scalar, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def full_like(x: _ArrayInput, fill_value: _Scalar, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
@overload
def arange(start: int | float, /, stop: int | float | None = ..., step: int | float = ..., *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def arange(start: int | float, /, stop: int | float | None = ..., step: int | float = ..., *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def arange(start: int | float, /, stop: int | float | None = ..., step: int | float = ..., *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
@overload
def linspace(start: int | float, stop: int | float, /, num: int, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ..., endpoint: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def linspace(start: int | float, stop: int | float, /, num: int, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ..., endpoint: _b.bool = ...) -> Array[_DType]: ...
@overload
def linspace(start: int | float, stop: int | float, /, num: int, *, dtype: str | None = ..., device: _Device = ..., endpoint: _b.bool = ...) -> Array[Scalar]: ...
@overload
def eye(n_rows: int, n_cols: int | None = ..., *, k: int = ..., dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def eye(n_rows: int, n_cols: int | None = ..., *, k: int = ..., dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def eye(n_rows: int, n_cols: int | None = ..., *, k: int = ..., dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
def concat(arrays: Sequence[_ArrayInput], /, *, axis: int | None = ...) -> Array[Scalar]: ...
def stack(arrays: Sequence[_ArrayInput], /, *, axis: int = ...) -> Array[Scalar]: ...
def nonzero(x: _ArrayInput, /) -> tuple[Array[np.intp], ...]: ...
def unstack(x: _ArrayInput, /, *, axis: int = ...) -> tuple[Array[Scalar], ...]: ...
def clip(x: _ArrayInput, /, min: _ArrayInput | _Scalar | None = ..., max: _ArrayInput | _Scalar | None = ...) -> Array[Scalar]: ...
def where(condition: _ArrayInput, x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
def take(x: Array[_DType], indices: _ArrayInput, /, *, axis: int | None = ...) -> Array[_DType]: ...
def take_along_axis(x: Array[_DType], indices: _ArrayInput, /, *, axis: int = ...) -> Array[_DType]: ...
def expand_dims(x: Array[_DType], /, axis: int) -> Array[_DType]: ...
def squeeze(x: Array[_DType], /, axis: _Axis = ...) -> Array[_DType]: ...
def broadcast_to(x: Array[_DType], /, shape: tuple[int, ...]) -> Array[_DType]: ...
def flip(x: Array[_DType], /, *, axis: _Axis = ...) -> Array[_DType]: ...
def moveaxis(x: Array[_DType], source: int | tuple[int, ...], destination: int | tuple[int, ...]) -> Array[_DType]: ...
def matrix_transpose(x: Array[_DType], /) -> Array[_DType]: ...
def roll(x: Array[_DType], /, shift: int | tuple[int, ...], *, axis: _Axis = ...) -> Array[_DType]: ...
def repeat(x: Array[_DType], repeats: int | _ArrayInput, /, *, axis: int | None = ...) -> Array[_DType]: ...
def tile(x: Array[_DType], repetitions: int | tuple[int, ...], /) -> Array[_DType]: ...
def sort(x: Array[_DType], /, *, axis: int = ..., descending: _b.bool = ..., stable: _b.bool = ...) -> Array[_DType]: ...
def argsort(x: _ArrayInput, /, *, axis: int = ..., descending: _b.bool = ..., stable: _b.bool = ...) -> Array[np.intp]: ...
def searchsorted(x1: _ArrayInput, x2: _ArrayInput, /, *, side: Literal['left', 'right'] = ..., sorter: _ArrayInput | None = ...) -> Array[np.intp]: ...
def tril(x: Array[_DType], /, *, k: int = ...) -> Array[_DType]: ...
def triu(x: Array[_DType], /, *, k: int = ...) -> Array[_DType]: ...
def tensordot(x1: _ArrayInput, x2: _ArrayInput, /, *, axes: int | tuple[Sequence[int], Sequence[int]] = ...) -> Array[Scalar]: ...
def vecdot(x1: _ArrayInput, x2: _ArrayInput, /, *, axis: int = ...) -> Array[Scalar]: ...
def diff(x: _ArrayInput, /, *, axis: int = ..., n: int = ..., prepend: _ArrayInput | None = ..., append: _ArrayInput | None = ...) -> Array[Scalar]: ...
def isin(element: _ArrayInput, test_elements: _ArrayInput, *, assume_unique: _b.bool = ..., invert: _b.bool = ...) -> Array[np.bool_]: ...
def unique_values(x: _ArrayInput, /) -> Array[Scalar]: ...
from typing import NamedTuple
class _UniqueAllResult(NamedTuple):
    values: Array[Scalar]
    indices: Array[np.intp]
    inverse_indices: Array[np.intp]
    counts: Array[np.intp]
class _UniqueCountsResult(NamedTuple):
    values: Array[Scalar]
    counts: Array[np.intp]
class _UniqueInverseResult(NamedTuple):
    values: Array[Scalar]
    inverse_indices: Array[np.intp]
def unique_all(x: _ArrayInput, /) -> _UniqueAllResult: ...
def unique_counts(x: _ArrayInput, /) -> _UniqueCountsResult: ...
def unique_inverse(x: _ArrayInput, /) -> _UniqueInverseResult: ...
class _FloatInfo:
    bits: int
    eps: float
    max: float
    min: float
    smallest_normal: float
    dtype: np.dtype[Scalar]
def finfo(type: _ArrayInput | _DTypeLike, /) -> _FloatInfo: ...
class _IntegerInfo(Protocol):
    @property
    def bits(self) -> int: ...
    @property
    def min(self) -> int: ...
    @property
    def max(self) -> int: ...
    @property
    def dtype(self) -> np.dtype[Scalar]: ...
def iinfo(type: _ArrayInput | _DTypeLike, /) -> _IntegerInfo: ...
class _EighResult(NamedTuple):
    eigenvalues: Array[Scalar]
    eigenvectors: Array[Scalar]
class _QRResult(NamedTuple):
    Q: Array[Scalar]
    R: Array[Scalar]
class _SlogdetResult(NamedTuple):
    sign: Array[Scalar]
    logabsdet: Array[Scalar]
class _SVDResult(NamedTuple):
    U: Array[Scalar]
    S: Array[Scalar]
    Vh: Array[Scalar]
class _Linalg:
    @staticmethod
    def cholesky(x: _ArrayInput, /, *, upper: _b.bool = ...) -> Array[Scalar]: ...
    @staticmethod
    def cross(x1: _ArrayInput, x2: _ArrayInput, /, *, axis: int = ...) -> Array[Scalar]: ...
    @staticmethod
    def det(x: _ArrayInput, /) -> Array[Scalar]: ...
    @staticmethod
    def diagonal(x: _ArrayInput, /, *, offset: int = ...) -> Array[Scalar]: ...
    @staticmethod
    def eigh(x: _ArrayInput, /) -> _EighResult: ...
    @staticmethod
    def eigvalsh(x: _ArrayInput, /) -> Array[Scalar]: ...
    @staticmethod
    def inv(x: _ArrayInput, /) -> Array[Scalar]: ...
    @staticmethod
    def matmul(x1: _ArrayInput, x2: _ArrayInput, /) -> Array[Scalar]: ...
    @staticmethod
    def matrix_norm(x: _ArrayInput, /, *, keepdims: _b.bool = ..., ord: int | float | Literal["fro", "nuc"] = ...) -> Array[Scalar]: ...
    @staticmethod
    def matrix_power(x: _ArrayInput, n: int, /) -> Array[Scalar]: ...
    @staticmethod
    def matrix_rank(x: _ArrayInput, /, *, rtol: float | _ArrayInput | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def matrix_transpose(x: Array[_DType], /) -> Array[_DType]: ...
    @staticmethod
    def outer(x1: _ArrayInput, x2: _ArrayInput, /) -> Array[Scalar]: ...
    @staticmethod
    def pinv(x: _ArrayInput, /, *, rtol: float | _ArrayInput | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def qr(x: _ArrayInput, /, *, mode: Literal["reduced", "complete"] = ...) -> _QRResult: ...
    @staticmethod
    def slogdet(x: _ArrayInput, /) -> _SlogdetResult: ...
    @staticmethod
    def solve(x1: _ArrayInput, x2: _ArrayInput, /) -> Array[Scalar]: ...
    @staticmethod
    def svd(x: _ArrayInput, /, *, full_matrices: _b.bool = ...) -> _SVDResult: ...
    @staticmethod
    def svdvals(x: _ArrayInput, /) -> Array[Scalar]: ...
    @staticmethod
    def vecdot(x1: _ArrayInput, x2: _ArrayInput, /, *, axis: int = ...) -> Array[Scalar]: ...
    @staticmethod
    def vector_norm(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ..., ord: int | float = ...) -> Array[Scalar]: ...
    @staticmethod
    def tensordot(x1: _ArrayInput, x2: _ArrayInput, /, *, axes: int | tuple[Sequence[int], Sequence[int]] = ...) -> Array[Scalar]: ...
    @staticmethod
    def trace(x: _ArrayInput, /, *, offset: int = ..., dtype: _DTypeLike | None = ...) -> Array[Scalar]: ...
linalg: _Linalg
class _FFT:
    @staticmethod
    def fft(x: _ArrayInput, /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def ifft(x: _ArrayInput, /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def rfft(x: _ArrayInput, /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def irfft(x: _ArrayInput, /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def hfft(x: _ArrayInput, /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def ihfft(x: _ArrayInput, /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def fftn(x: _ArrayInput, /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def ifftn(x: _ArrayInput, /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def fft2(x: _ArrayInput, /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def ifft2(x: _ArrayInput, /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def rfftn(x: _ArrayInput, /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def irfftn(x: _ArrayInput, /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def rfft2(x: _ArrayInput, /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def irfft2(x: _ArrayInput, /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def fftfreq(n: int, /, *, d: float = ..., dtype: _DTypeLike | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @staticmethod
    def rfftfreq(n: int, /, *, d: float = ..., dtype: _DTypeLike | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @staticmethod
    def fftshift(x: _ArrayInput, /, *, axes: _Axis = ...) -> Array[Scalar]: ...
    @staticmethod
    def ifftshift(x: _ArrayInput, /, *, axes: _Axis = ...) -> Array[Scalar]: ...
fft: _FFT
class _NamespaceInfo:
    def capabilities(self) -> dict[str, object]: ...
    def devices(self) -> tuple[str, ...]: ...
    def default_device(self) -> str: ...
    def default_dtypes(self, *, device: _Device = ...) -> dict[str, _DTypeLike]: ...
    def dtypes(self, *, device: _Device = ..., kind: str | tuple[str, ...] | None = ...) -> dict[str, _DTypeLike]: ...
def __array_namespace_info__() -> _NamespaceInfo: ...

# Generated namespace protocol: scripts/generate-namespace-stub.py
class _Namespace(Protocol):
    @overload
    @staticmethod
    def asarray(obj: object, /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ..., copy: _b.bool | None = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def asarray(obj: object, /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ..., copy: _b.bool | None = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def asarray(obj: Array[_DType] | np.ndarray[tuple[int, ...], np.dtype[_DType]], /, *, dtype: None = ..., device: _Device = ..., copy: _b.bool | None = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def asarray(obj: _NativeArray, /, *, dtype: None = ..., device: _Device = ..., copy: _b.bool | None = ...) -> Array[np.uint8]: ...
    @overload
    @staticmethod
    def asarray(obj: object, /, *, dtype: str | None = ..., device: _Device = ..., copy: _b.bool | None = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def astype(x: _ArrayInput, dtype: type[np.bool_] | np.dtype[np.bool_], /, *, copy: _b.bool = ..., device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def astype(x: _ArrayInput, dtype: type[_DType] | np.dtype[_DType], /, *, copy: _b.bool = ..., device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def astype(x: _ArrayInput, dtype: str, /, *, copy: _b.bool = ..., device: _Device = ...) -> Array[Scalar]: ...
    @staticmethod
    def reshape(x: Array[_DType], /, shape: tuple[int, ...], *, copy: _b.bool | None = ...) -> Array[_DType]: ...
    @staticmethod
    def permute_dims(x: Array[_DType], /, axes: tuple[int, ...]) -> Array[_DType]: ...
    @staticmethod
    def from_dlpack(x: object, /, *, device: _Device = ..., copy: _b.bool | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def broadcast_arrays(*arrays: _ArrayInput) -> tuple[Array[Scalar], ...]: ...
    @staticmethod
    def meshgrid(*arrays: _ArrayInput, indexing: Literal['xy', 'ij'] = ...) -> tuple[Array[Scalar], ...]: ...
    @staticmethod
    def broadcast_shapes(*shapes: tuple[int, ...]) -> tuple[int, ...]: ...
    @staticmethod
    def can_cast(from_: _ArrayInput | _DTypeLike, to: _DTypeLike) -> _b.bool: ...
    @staticmethod
    def isdtype(dtype: _DTypeLike, kind: object) -> _b.bool: ...
    @staticmethod
    def result_type(*arrays_and_dtypes: _ArrayInput | _DTypeLike) -> np.dtype[Scalar]: ...
    @staticmethod
    def abs(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def acos(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def acosh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def asin(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def asinh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def atan(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def atanh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def bitwise_invert(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def ceil(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def conj(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def cos(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def cosh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def exp(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def expm1(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def floor(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def imag(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def isfinite(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def isinf(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def isnan(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def log(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def log1p(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def log2(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def log10(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def logical_not(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def negative(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def positive(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def real(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def round(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def sign(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def signbit(x: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def sin(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def sinh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def sqrt(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def square(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def tan(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def tanh(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def trunc(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def reciprocal(x: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def add(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def atan2(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def bitwise_and(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def bitwise_left_shift(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def bitwise_or(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def bitwise_right_shift(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def bitwise_xor(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def copysign(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def divide(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def equal(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def floor_divide(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def greater(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def greater_equal(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def hypot(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def less(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def less_equal(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def logaddexp(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def logical_and(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def logical_or(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def logical_xor(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def matmul(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def maximum(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def minimum(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def multiply(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def not_equal(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[np.bool_]: ...
    @staticmethod
    def pow(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def remainder(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def subtract(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def nextafter(x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def sum(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: type[np.bool_] | np.dtype[np.bool_], keepdims: _b.bool = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def sum(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: type[_DType] | np.dtype[_DType], keepdims: _b.bool = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def sum(x: Array[_Unsigned], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[np.uint64]: ...
    @overload
    @staticmethod
    def sum(x: Array[_Signed], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[np.int64]: ...
    @overload
    @staticmethod
    def sum(x: Array[_Inexact], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[_Inexact]: ...
    @overload
    @staticmethod
    def sum(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: str | None = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def prod(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: type[np.bool_] | np.dtype[np.bool_], keepdims: _b.bool = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def prod(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: type[_DType] | np.dtype[_DType], keepdims: _b.bool = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def prod(x: Array[_Unsigned], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[np.uint64]: ...
    @overload
    @staticmethod
    def prod(x: Array[_Signed], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[np.int64]: ...
    @overload
    @staticmethod
    def prod(x: Array[_Inexact], /, *, axis: _Axis = ..., dtype: None = ..., keepdims: _b.bool = ...) -> Array[_Inexact]: ...
    @overload
    @staticmethod
    def prod(x: _ArrayInput, /, *, axis: _Axis = ..., dtype: str | None = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def cumulative_sum(x: _ArrayInput, /, *, axis: int | None = ..., dtype: type[np.bool_] | np.dtype[np.bool_], include_initial: _b.bool = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def cumulative_sum(x: _ArrayInput, /, *, axis: int | None = ..., dtype: type[_DType] | np.dtype[_DType], include_initial: _b.bool = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def cumulative_sum(x: Array[_Unsigned], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[np.uint64]: ...
    @overload
    @staticmethod
    def cumulative_sum(x: Array[_Signed], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[np.int64]: ...
    @overload
    @staticmethod
    def cumulative_sum(x: Array[_Inexact], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[_Inexact]: ...
    @overload
    @staticmethod
    def cumulative_sum(x: _ArrayInput, /, *, axis: int | None = ..., dtype: str | None = ..., include_initial: _b.bool = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def cumulative_prod(x: _ArrayInput, /, *, axis: int | None = ..., dtype: type[np.bool_] | np.dtype[np.bool_], include_initial: _b.bool = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def cumulative_prod(x: _ArrayInput, /, *, axis: int | None = ..., dtype: type[_DType] | np.dtype[_DType], include_initial: _b.bool = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def cumulative_prod(x: Array[_Unsigned], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[np.uint64]: ...
    @overload
    @staticmethod
    def cumulative_prod(x: Array[_Signed], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[np.int64]: ...
    @overload
    @staticmethod
    def cumulative_prod(x: Array[_Inexact], /, *, axis: int | None = ..., dtype: None = ..., include_initial: _b.bool = ...) -> Array[_Inexact]: ...
    @overload
    @staticmethod
    def cumulative_prod(x: _ArrayInput, /, *, axis: int | None = ..., dtype: str | None = ..., include_initial: _b.bool = ...) -> Array[Scalar]: ...
    @staticmethod
    def mean(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
    @staticmethod
    def std(x: _ArrayInput, /, *, axis: _Axis = ..., correction: float = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
    @staticmethod
    def var(x: _ArrayInput, /, *, axis: _Axis = ..., correction: float = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
    @staticmethod
    def max(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
    @staticmethod
    def min(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Scalar]: ...
    @staticmethod
    def all(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[np.bool_]: ...
    @staticmethod
    def any(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[np.bool_]: ...
    @staticmethod
    def count_nonzero(x: _ArrayInput, /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[np.intp]: ...
    @staticmethod
    def argmax(x: _ArrayInput, /, *, axis: int | None = ..., keepdims: _b.bool = ...) -> Array[np.intp]: ...
    @staticmethod
    def argmin(x: _ArrayInput, /, *, axis: int | None = ..., keepdims: _b.bool = ...) -> Array[np.intp]: ...
    @overload
    @staticmethod
    def empty(shape: _Shape, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def empty(shape: _Shape, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def empty(shape: _Shape, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def empty_like(x: _ArrayInput, /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def empty_like(x: _ArrayInput, /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def empty_like(x: Array[_DType], /, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def empty_like(x: _ArrayInput, /, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def ones(shape: _Shape, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def ones(shape: _Shape, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def ones(shape: _Shape, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def ones_like(x: _ArrayInput, /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def ones_like(x: _ArrayInput, /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def ones_like(x: Array[_DType], /, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def ones_like(x: _ArrayInput, /, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def zeros(shape: _Shape, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def zeros(shape: _Shape, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def zeros(shape: _Shape, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def zeros_like(x: _ArrayInput, /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def zeros_like(x: _ArrayInput, /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def zeros_like(x: Array[_DType], /, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def zeros_like(x: _ArrayInput, /, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def full(shape: _Shape, fill_value: _Scalar, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def full(shape: _Shape, fill_value: _Scalar, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def full(shape: _Shape, fill_value: _Scalar, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def full_like(x: _ArrayInput, fill_value: _Scalar, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def full_like(x: _ArrayInput, fill_value: _Scalar, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def full_like(x: Array[_DType], fill_value: _Scalar, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def full_like(x: _ArrayInput, fill_value: _Scalar, *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def arange(start: int | float, /, stop: int | float | None = ..., step: int | float = ..., *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def arange(start: int | float, /, stop: int | float | None = ..., step: int | float = ..., *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def arange(start: int | float, /, stop: int | float | None = ..., step: int | float = ..., *, dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def linspace(start: int | float, stop: int | float, /, num: int, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ..., endpoint: _b.bool = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def linspace(start: int | float, stop: int | float, /, num: int, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ..., endpoint: _b.bool = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def linspace(start: int | float, stop: int | float, /, num: int, *, dtype: str | None = ..., device: _Device = ..., endpoint: _b.bool = ...) -> Array[Scalar]: ...
    @overload
    @staticmethod
    def eye(n_rows: int, n_cols: int | None = ..., *, k: int = ..., dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
    @overload
    @staticmethod
    def eye(n_rows: int, n_cols: int | None = ..., *, k: int = ..., dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
    @overload
    @staticmethod
    def eye(n_rows: int, n_cols: int | None = ..., *, k: int = ..., dtype: str | None = ..., device: _Device = ...) -> Array[Scalar]: ...
    @staticmethod
    def concat(arrays: Sequence[_ArrayInput], /, *, axis: int | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def stack(arrays: Sequence[_ArrayInput], /, *, axis: int = ...) -> Array[Scalar]: ...
    @staticmethod
    def nonzero(x: _ArrayInput, /) -> tuple[Array[np.intp], ...]: ...
    @staticmethod
    def unstack(x: _ArrayInput, /, *, axis: int = ...) -> tuple[Array[Scalar], ...]: ...
    @staticmethod
    def clip(x: _ArrayInput, /, min: _ArrayInput | _Scalar | None = ..., max: _ArrayInput | _Scalar | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def where(condition: _ArrayInput, x1: _ArrayInput | _Scalar, x2: _ArrayInput | _Scalar, /) -> Array[Scalar]: ...
    @staticmethod
    def take(x: Array[_DType], indices: _ArrayInput, /, *, axis: int | None = ...) -> Array[_DType]: ...
    @staticmethod
    def take_along_axis(x: Array[_DType], indices: _ArrayInput, /, *, axis: int = ...) -> Array[_DType]: ...
    @staticmethod
    def expand_dims(x: Array[_DType], /, axis: int) -> Array[_DType]: ...
    @staticmethod
    def squeeze(x: Array[_DType], /, axis: _Axis = ...) -> Array[_DType]: ...
    @staticmethod
    def broadcast_to(x: Array[_DType], /, shape: tuple[int, ...]) -> Array[_DType]: ...
    @staticmethod
    def flip(x: Array[_DType], /, *, axis: _Axis = ...) -> Array[_DType]: ...
    @staticmethod
    def moveaxis(x: Array[_DType], source: int | tuple[int, ...], destination: int | tuple[int, ...]) -> Array[_DType]: ...
    @staticmethod
    def matrix_transpose(x: Array[_DType], /) -> Array[_DType]: ...
    @staticmethod
    def roll(x: Array[_DType], /, shift: int | tuple[int, ...], *, axis: _Axis = ...) -> Array[_DType]: ...
    @staticmethod
    def repeat(x: Array[_DType], repeats: int | _ArrayInput, /, *, axis: int | None = ...) -> Array[_DType]: ...
    @staticmethod
    def tile(x: Array[_DType], repetitions: int | tuple[int, ...], /) -> Array[_DType]: ...
    @staticmethod
    def sort(x: Array[_DType], /, *, axis: int = ..., descending: _b.bool = ..., stable: _b.bool = ...) -> Array[_DType]: ...
    @staticmethod
    def argsort(x: _ArrayInput, /, *, axis: int = ..., descending: _b.bool = ..., stable: _b.bool = ...) -> Array[np.intp]: ...
    @staticmethod
    def searchsorted(x1: _ArrayInput, x2: _ArrayInput, /, *, side: Literal['left', 'right'] = ..., sorter: _ArrayInput | None = ...) -> Array[np.intp]: ...
    @staticmethod
    def tril(x: Array[_DType], /, *, k: int = ...) -> Array[_DType]: ...
    @staticmethod
    def triu(x: Array[_DType], /, *, k: int = ...) -> Array[_DType]: ...
    @staticmethod
    def tensordot(x1: _ArrayInput, x2: _ArrayInput, /, *, axes: int | tuple[Sequence[int], Sequence[int]] = ...) -> Array[Scalar]: ...
    @staticmethod
    def vecdot(x1: _ArrayInput, x2: _ArrayInput, /, *, axis: int = ...) -> Array[Scalar]: ...
    @staticmethod
    def diff(x: _ArrayInput, /, *, axis: int = ..., n: int = ..., prepend: _ArrayInput | None = ..., append: _ArrayInput | None = ...) -> Array[Scalar]: ...
    @staticmethod
    def isin(element: _ArrayInput, test_elements: _ArrayInput, *, assume_unique: _b.bool = ..., invert: _b.bool = ...) -> Array[np.bool_]: ...
    @staticmethod
    def unique_values(x: _ArrayInput, /) -> Array[Scalar]: ...
    @staticmethod
    def unique_all(x: _ArrayInput, /) -> _UniqueAllResult: ...
    @staticmethod
    def unique_counts(x: _ArrayInput, /) -> _UniqueCountsResult: ...
    @staticmethod
    def unique_inverse(x: _ArrayInput, /) -> _UniqueInverseResult: ...
    @staticmethod
    def finfo(type: _ArrayInput | _DTypeLike, /) -> _FloatInfo: ...
    @staticmethod
    def iinfo(type: _ArrayInput | _DTypeLike, /) -> _IntegerInfo: ...
    @staticmethod
    def __array_namespace_info__() -> _NamespaceInfo: ...
    @property
    def bool(self) -> type[np.bool]: ...
    @property
    def uint8(self) -> type[np.uint8]: ...
    @property
    def uint16(self) -> type[np.uint16]: ...
    @property
    def uint32(self) -> type[np.uint32]: ...
    @property
    def uint64(self) -> type[np.uint64]: ...
    @property
    def int8(self) -> type[np.int8]: ...
    @property
    def int16(self) -> type[np.int16]: ...
    @property
    def int32(self) -> type[np.int32]: ...
    @property
    def int64(self) -> type[np.int64]: ...
    @property
    def float32(self) -> type[np.float32]: ...
    @property
    def float64(self) -> type[np.float64]: ...
    @property
    def complex64(self) -> type[np.complex64]: ...
    @property
    def complex128(self) -> type[np.complex128]: ...
    @property
    def linalg(self) -> _Linalg: ...
    @property
    def fft(self) -> _FFT: ...
    @property
    def e(self) -> float: ...
    @property
    def pi(self) -> float: ...
    @property
    def inf(self) -> float: ...
    @property
    def nan(self) -> float: ...
    @property
    def newaxis(self) -> None: ...
    @property
    def __array_api_version__(self) -> str: ...
    @property
    def __version__(self) -> str: ...
    @property
    def StorageWideningWarning(self) -> type[StorageWideningWarning]: ...
    @property
    def StorageWideningError(self) -> type[StorageWideningError]: ...
    @staticmethod
    def set_strict(enabled: _b.bool = ...) -> None: ...
    @staticmethod
    def strict(enabled: _b.bool = ...) -> AbstractContextManager[None]: ...
