import builtins as _b
from collections.abc import Iterator, Sequence
from contextlib import AbstractContextManager
from types import ModuleType, EllipsisType
from typing import Any, Literal, SupportsIndex, Generic, overload
from typing_extensions import TypeVar
from .. import Array as _NativeArray
import numpy as np
from numpy.typing import NDArray, DTypeLike
from ._policy import StorageWideningWarning as StorageWideningWarning, StorageWideningError as StorageWideningError, set_strict as set_strict, strict as strict

_DType = TypeVar("_DType", bound=np.generic, default=Any)

_OtherDType = TypeVar("_OtherDType", bound=np.generic)

_Scalar = _b.bool | int | float | complex
_Shape = int | tuple[int, ...]
_Axis = int | tuple[int, ...] | None
_IndexItem = SupportsIndex | slice | EllipsisType | None | Array[Any] | NDArray[Any]
_Index = _IndexItem | tuple[_IndexItem, ...]
_Device = Literal['cpu'] | None
__array_api_version__: str
__version__: str
e: float
pi: float
inf: float
nan: float
newaxis: None
from numpy import bool as bool
from numpy import uint8 as uint8
from numpy import uint16 as uint16
from numpy import uint32 as uint32
from numpy import uint64 as uint64
from numpy import int8 as int8
from numpy import int16 as int16
from numpy import int32 as int32
from numpy import int64 as int64
from numpy import float32 as float32
from numpy import float64 as float64
from numpy import complex64 as complex64
from numpy import complex128 as complex128

class Array(Generic[_DType]):
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def dtype(self) -> np.dtype[_DType]: ...
    @property
    def device(self) -> Literal['cpu']: ...
    @property
    def storage_bits(self) -> int: ...
    @property
    def storage_nbytes(self) -> int: ...
    @property
    def T(self) -> Array[_DType]: ...
    @property
    def mT(self) -> Array[_DType]: ...
    def __getitem__(self, key: _Index, /) -> Array[_DType]: ...
    def __setitem__(self, key: _Index, value: Array[Any] | _Scalar | Sequence[object] | NDArray[Any], /) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Array[_DType]]: ...
    @overload
    def __array__(self, dtype: None = ..., copy: _b.bool | None = ...) -> NDArray[_DType]: ...
    @overload
    def __array__(self, dtype: type[_OtherDType] | np.dtype[_OtherDType], copy: _b.bool | None = ...) -> NDArray[_OtherDType]: ...
    @overload
    def __array__(self, dtype: DTypeLike | None = ..., copy: _b.bool | None = ...) -> NDArray[Any]: ...
    def __array_namespace__(self, *, api_version: str | None = ...) -> ModuleType: ...
    def to_device(self, device: _Device, /, *, stream: None = ...) -> Array[_DType]: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(self, *, stream: None = ..., max_version: tuple[int, int] | None = ..., dl_device: tuple[int, int] | None = ..., copy: _b.bool | None = ...) -> object: ...
    def __bool__(self) -> _b.bool: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __add__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __radd__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __iadd__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __sub__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rsub__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __isub__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __mul__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rmul__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __imul__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __truediv__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rtruediv__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __itruediv__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __floordiv__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rfloordiv__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __ifloordiv__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __mod__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rmod__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __imod__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __pow__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rpow__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __ipow__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __matmul__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rmatmul__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __imatmul__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __and__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rand__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __iand__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __or__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __ror__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __ior__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __xor__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rxor__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __ixor__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __lshift__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rlshift__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __ilshift__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __rshift__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __rrshift__(self, other: Array[Any] | _Scalar) -> Array[Any]: ...
    def __irshift__(self, other: Array[Any] | _Scalar) -> Array[_DType]: ...
    def __eq__(self, other: Array[Any] | _Scalar) -> Array[np.bool_]: ...  # type: ignore[override]
    def __ne__(self, other: Array[Any] | _Scalar) -> Array[np.bool_]: ...  # type: ignore[override]
    def __lt__(self, other: Array[Any] | _Scalar) -> Array[np.bool_]: ...
    def __le__(self, other: Array[Any] | _Scalar) -> Array[np.bool_]: ...
    def __gt__(self, other: Array[Any] | _Scalar) -> Array[np.bool_]: ...
    def __ge__(self, other: Array[Any] | _Scalar) -> Array[np.bool_]: ...
    def __neg__(self) -> Array[Any]: ...
    def __pos__(self) -> Array[Any]: ...
    def __abs__(self) -> Array[Any]: ...
    def __invert__(self) -> Array[Any]: ...

@overload
def asarray(obj: object, /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ..., copy: _b.bool | None = ...) -> Array[np.bool_]: ...
@overload
def asarray(obj: object, /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ..., copy: _b.bool | None = ...) -> Array[_DType]: ...
@overload
def asarray(obj: Array[_DType] | NDArray[_DType], /, *, dtype: None = ..., device: _Device = ..., copy: _b.bool | None = ...) -> Array[_DType]: ...
@overload
def asarray(obj: _NativeArray, /, *, dtype: None = ..., device: _Device = ..., copy: _b.bool | None = ...) -> Array[np.uint8]: ...
@overload
def asarray(obj: object, /, *, dtype: str | None = ..., device: _Device = ..., copy: _b.bool | None = ...) -> Array[Any]: ...
@overload
def astype(x: Array[Any], dtype: type[np.bool_] | np.dtype[np.bool_], /, *, copy: _b.bool = ..., device: _Device = ...) -> Array[np.bool_]: ...
@overload
def astype(x: Array[Any], dtype: type[_DType] | np.dtype[_DType], /, *, copy: _b.bool = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def astype(x: Array[Any], dtype: str, /, *, copy: _b.bool = ..., device: _Device = ...) -> Array[Any]: ...
def reshape(x: Array[_DType], /, shape: tuple[int, ...], *, copy: _b.bool | None = ...) -> Array[_DType]: ...
def permute_dims(x: Array[_DType], /, axes: tuple[int, ...]) -> Array[_DType]: ...
def from_dlpack(x: object, /, *, device: _Device = ..., copy: _b.bool | None = ...) -> Array[Any]: ...
def broadcast_arrays(*arrays: Array[Any]) -> tuple[Array[Any], ...]: ...
def meshgrid(*arrays: Array[Any], indexing: Literal['xy', 'ij'] = ...) -> tuple[Array[Any], ...]: ...
def broadcast_shapes(*shapes: tuple[int, ...]) -> tuple[int, ...]: ...
def can_cast(from_: Array[Any] | DTypeLike, to: DTypeLike) -> _b.bool: ...
def isdtype(dtype: DTypeLike, kind: object) -> _b.bool: ...
def result_type(*arrays_and_dtypes: Array[Any] | DTypeLike) -> np.dtype[Any]: ...
def abs(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def acos(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def acosh(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def asin(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def asinh(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def atan(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def atanh(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def bitwise_invert(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def ceil(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def conj(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def cos(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def cosh(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def exp(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def expm1(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def floor(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def imag(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def isfinite(x: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def isinf(x: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def isnan(x: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def log(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def log1p(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def log2(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def log10(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def logical_not(x: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def negative(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def positive(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def real(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def round(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def sign(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def signbit(x: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def sin(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def sinh(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def sqrt(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def square(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def tan(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def tanh(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def trunc(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def reciprocal(x: Array[Any] | _Scalar, /) -> Array[Any]: ...
def add(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def atan2(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def bitwise_and(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def bitwise_left_shift(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def bitwise_or(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def bitwise_right_shift(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def bitwise_xor(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def copysign(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def divide(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def equal(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def floor_divide(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def greater(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def greater_equal(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def hypot(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def less(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def less_equal(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def logaddexp(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def logical_and(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def logical_or(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def logical_xor(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def matmul(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def maximum(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def minimum(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def multiply(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def not_equal(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[np.bool_]: ...
def pow(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def remainder(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def subtract(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def nextafter(x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
@overload
def sum(x: Array[Any], /, *, axis: _Axis = ..., dtype: type[np.bool_] | np.dtype[np.bool_], keepdims: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def sum(x: Array[Any], /, *, axis: _Axis = ..., dtype: type[_DType] | np.dtype[_DType], keepdims: _b.bool = ...) -> Array[_DType]: ...
@overload
def sum(x: Array[Any], /, *, axis: _Axis = ..., dtype: str | None = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
@overload
def prod(x: Array[Any], /, *, axis: _Axis = ..., dtype: type[np.bool_] | np.dtype[np.bool_], keepdims: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def prod(x: Array[Any], /, *, axis: _Axis = ..., dtype: type[_DType] | np.dtype[_DType], keepdims: _b.bool = ...) -> Array[_DType]: ...
@overload
def prod(x: Array[Any], /, *, axis: _Axis = ..., dtype: str | None = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
@overload
def cumulative_sum(x: Array[Any], /, *, axis: int | None = ..., dtype: type[np.bool_] | np.dtype[np.bool_], include_initial: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def cumulative_sum(x: Array[Any], /, *, axis: int | None = ..., dtype: type[_DType] | np.dtype[_DType], include_initial: _b.bool = ...) -> Array[_DType]: ...
@overload
def cumulative_sum(x: Array[Any], /, *, axis: int | None = ..., dtype: str | None = ..., include_initial: _b.bool = ...) -> Array[Any]: ...
@overload
def cumulative_prod(x: Array[Any], /, *, axis: int | None = ..., dtype: type[np.bool_] | np.dtype[np.bool_], include_initial: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def cumulative_prod(x: Array[Any], /, *, axis: int | None = ..., dtype: type[_DType] | np.dtype[_DType], include_initial: _b.bool = ...) -> Array[_DType]: ...
@overload
def cumulative_prod(x: Array[Any], /, *, axis: int | None = ..., dtype: str | None = ..., include_initial: _b.bool = ...) -> Array[Any]: ...
def mean(x: Array[Any], /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
def std(x: Array[Any], /, *, axis: _Axis = ..., correction: float = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
def var(x: Array[Any], /, *, axis: _Axis = ..., correction: float = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
def max(x: Array[Any], /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
def min(x: Array[Any], /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
def all(x: Array[Any], /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[np.bool_]: ...
def any(x: Array[Any], /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[np.bool_]: ...
def count_nonzero(x: Array[Any], /, *, axis: _Axis = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
def argmax(x: Array[Any], /, *, axis: int | None = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
def argmin(x: Array[Any], /, *, axis: int | None = ..., keepdims: _b.bool = ...) -> Array[Any]: ...
@overload
def empty(shape: _Shape, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def empty(shape: _Shape, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def empty(shape: _Shape, *, dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
@overload
def empty_like(x: Array[Any], /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def empty_like(x: Array[Any], /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def empty_like(x: Array[_DType], /, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def empty_like(x: Array[Any], /, *, dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
@overload
def ones(shape: _Shape, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def ones(shape: _Shape, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def ones(shape: _Shape, *, dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
@overload
def ones_like(x: Array[Any], /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def ones_like(x: Array[Any], /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def ones_like(x: Array[_DType], /, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def ones_like(x: Array[Any], /, *, dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
@overload
def zeros(shape: _Shape, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def zeros(shape: _Shape, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def zeros(shape: _Shape, *, dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
@overload
def zeros_like(x: Array[Any], /, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def zeros_like(x: Array[Any], /, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def zeros_like(x: Array[_DType], /, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def zeros_like(x: Array[Any], /, *, dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
@overload
def full(shape: _Shape, fill_value: _Scalar, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def full(shape: _Shape, fill_value: _Scalar, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def full(shape: _Shape, fill_value: _Scalar, *, dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
@overload
def full_like(x: Array[Any], fill_value: _Scalar, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def full_like(x: Array[Any], fill_value: _Scalar, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def full_like(x: Array[_DType], fill_value: _Scalar, *, dtype: None = ..., device: _Device = ...) -> Array[_DType]: ...
@overload
def full_like(x: Array[Any], fill_value: _Scalar, *, dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
@overload
def arange(start: int | float, /, stop: int | float | None = ..., step: int | float = ..., *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def arange(start: int | float, /, stop: int | float | None = ..., step: int | float = ..., *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def arange(start: int | float, /, stop: int | float | None = ..., step: int | float = ..., *, dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
@overload
def linspace(start: int | float, stop: int | float, /, num: int, *, dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ..., endpoint: _b.bool = ...) -> Array[np.bool_]: ...
@overload
def linspace(start: int | float, stop: int | float, /, num: int, *, dtype: type[_DType] | np.dtype[_DType], device: _Device = ..., endpoint: _b.bool = ...) -> Array[_DType]: ...
@overload
def linspace(start: int | float, stop: int | float, /, num: int, *, dtype: str | None = ..., device: _Device = ..., endpoint: _b.bool = ...) -> Array[Any]: ...
@overload
def eye(n_rows: int, n_cols: int | None = ..., *, k: int = ..., dtype: type[np.bool_] | np.dtype[np.bool_], device: _Device = ...) -> Array[np.bool_]: ...
@overload
def eye(n_rows: int, n_cols: int | None = ..., *, k: int = ..., dtype: type[_DType] | np.dtype[_DType], device: _Device = ...) -> Array[_DType]: ...
@overload
def eye(n_rows: int, n_cols: int | None = ..., *, k: int = ..., dtype: str | None = ..., device: _Device = ...) -> Array[Any]: ...
def concat(arrays: Sequence[Array[Any]], /, *, axis: int | None = ...) -> Array[Any]: ...
def stack(arrays: Sequence[Array[Any]], /, *, axis: int = ...) -> Array[Any]: ...
def nonzero(x: Array[Any], /) -> tuple[Array[Any], ...]: ...
def unstack(x: Array[Any], /, *, axis: int = ...) -> tuple[Array[Any], ...]: ...
def clip(x: Array[Any], /, min: Array[Any] | _Scalar | None = ..., max: Array[Any] | _Scalar | None = ...) -> Array[Any]: ...
def where(condition: Array[Any], x1: Array[Any] | _Scalar, x2: Array[Any] | _Scalar, /) -> Array[Any]: ...
def take(x: Array[_DType], indices: Array[Any], /, *, axis: int | None = ...) -> Array[_DType]: ...
def take_along_axis(x: Array[_DType], indices: Array[Any], /, *, axis: int = ...) -> Array[_DType]: ...
def expand_dims(x: Array[_DType], /, axis: int) -> Array[_DType]: ...
def squeeze(x: Array[_DType], /, axis: _Axis = ...) -> Array[_DType]: ...
def broadcast_to(x: Array[_DType], /, shape: tuple[int, ...]) -> Array[_DType]: ...
def flip(x: Array[_DType], /, *, axis: _Axis = ...) -> Array[_DType]: ...
def moveaxis(x: Array[_DType], source: int | tuple[int, ...], destination: int | tuple[int, ...]) -> Array[_DType]: ...
def matrix_transpose(x: Array[_DType], /) -> Array[_DType]: ...
def roll(x: Array[_DType], /, shift: int | tuple[int, ...], *, axis: _Axis = ...) -> Array[_DType]: ...
def repeat(x: Array[_DType], repeats: int | Array[Any], /, *, axis: int | None = ...) -> Array[_DType]: ...
def tile(x: Array[_DType], repetitions: int | tuple[int, ...], /) -> Array[_DType]: ...
def sort(x: Array[_DType], /, *, axis: int = ..., descending: _b.bool = ..., stable: _b.bool = ...) -> Array[_DType]: ...
def argsort(x: Array[Any], /, *, axis: int = ..., descending: _b.bool = ..., stable: _b.bool = ...) -> Array[Any]: ...
def searchsorted(x1: Array[Any], x2: Array[Any], /, *, side: Literal['left', 'right'] = ..., sorter: Array[Any] | None = ...) -> Array[Any]: ...
def tril(x: Array[_DType], /, *, k: int = ...) -> Array[_DType]: ...
def triu(x: Array[_DType], /, *, k: int = ...) -> Array[_DType]: ...
def tensordot(x1: Array[Any], x2: Array[Any], /, *, axes: int | tuple[Sequence[int], Sequence[int]] = ...) -> Array[Any]: ...
def vecdot(x1: Array[Any], x2: Array[Any], /, *, axis: int = ...) -> Array[Any]: ...
def diff(x: Array[Any], /, *, axis: int = ..., n: int = ..., prepend: Array[Any] | None = ..., append: Array[Any] | None = ...) -> Array[Any]: ...
def isin(element: Array[Any], test_elements: Array[Any], *, assume_unique: _b.bool = ..., invert: _b.bool = ...) -> Array[np.bool_]: ...
def unique_values(x: Array[Any], /) -> Array[Any]: ...
from typing import NamedTuple
class _UniqueAllResult(NamedTuple):
    values: Array[Any]
    indices: Array[Any]
    inverse_indices: Array[Any]
    counts: Array[Any]
class _UniqueCountsResult(NamedTuple):
    values: Array[Any]
    counts: Array[Any]
class _UniqueInverseResult(NamedTuple):
    values: Array[Any]
    inverse_indices: Array[Any]
def unique_all(x: Array[Any], /) -> _UniqueAllResult: ...
def unique_counts(x: Array[Any], /) -> _UniqueCountsResult: ...
def unique_inverse(x: Array[Any], /) -> _UniqueInverseResult: ...
class _FloatInfo:
    bits: int
    eps: float
    max: float
    min: float
    smallest_normal: float
    dtype: np.dtype[Any]
def finfo(type: Array[Any] | DTypeLike, /) -> _FloatInfo: ...
def iinfo(type: Array[Any] | DTypeLike, /) -> np.iinfo[Any]: ...
class _EighResult(NamedTuple):
    eigenvalues: Array[Any]
    eigenvectors: Array[Any]
class _QRResult(NamedTuple):
    Q: Array[Any]
    R: Array[Any]
class _SlogdetResult(NamedTuple):
    sign: Array[Any]
    logabsdet: Array[Any]
class _SVDResult(NamedTuple):
    U: Array[Any]
    S: Array[Any]
    Vh: Array[Any]
class _Linalg:
    @staticmethod
    def cholesky(x: Array[Any], /, *, upper: _b.bool = ...) -> Array[Any]: ...
    @staticmethod
    def cross(x1: Array[Any], x2: Array[Any], /, *, axis: int = ...) -> Array[Any]: ...
    @staticmethod
    def det(x: Array[Any], /) -> Array[Any]: ...
    @staticmethod
    def diagonal(x: Array[Any], /, *, offset: int = ...) -> Array[Any]: ...
    @staticmethod
    def eigh(x: Array[Any], /) -> _EighResult: ...
    @staticmethod
    def eigvalsh(x: Array[Any], /) -> Array[Any]: ...
    @staticmethod
    def inv(x: Array[Any], /) -> Array[Any]: ...
    @staticmethod
    def matmul(x1: Array[Any], x2: Array[Any], /) -> Array[Any]: ...
    @staticmethod
    def matrix_norm(x: Array[Any], /, *, keepdims: _b.bool = ..., ord: int | float | Literal["fro", "nuc"] = ...) -> Array[Any]: ...
    @staticmethod
    def matrix_power(x: Array[Any], n: int, /) -> Array[Any]: ...
    @staticmethod
    def matrix_rank(x: Array[Any], /, *, rtol: float | Array[Any] | None = ...) -> Array[Any]: ...
    @staticmethod
    def matrix_transpose(x: Array[_DType], /) -> Array[_DType]: ...
    @staticmethod
    def outer(x1: Array[Any], x2: Array[Any], /) -> Array[Any]: ...
    @staticmethod
    def pinv(x: Array[Any], /, *, rtol: float | Array[Any] | None = ...) -> Array[Any]: ...
    @staticmethod
    def qr(x: Array[Any], /, *, mode: Literal["reduced", "complete"] = ...) -> _QRResult: ...
    @staticmethod
    def slogdet(x: Array[Any], /) -> _SlogdetResult: ...
    @staticmethod
    def solve(x1: Array[Any], x2: Array[Any], /) -> Array[Any]: ...
    @staticmethod
    def svd(x: Array[Any], /, *, full_matrices: _b.bool = ...) -> _SVDResult: ...
    @staticmethod
    def svdvals(x: Array[Any], /) -> Array[Any]: ...
    @staticmethod
    def vecdot(x1: Array[Any], x2: Array[Any], /, *, axis: int = ...) -> Array[Any]: ...
    @staticmethod
    def vector_norm(x: Array[Any], /, *, axis: _Axis = ..., keepdims: _b.bool = ..., ord: int | float = ...) -> Array[Any]: ...
    @staticmethod
    def tensordot(x1: Array[Any], x2: Array[Any], /, *, axes: int | tuple[Sequence[int], Sequence[int]] = ...) -> Array[Any]: ...
    @staticmethod
    def trace(x: Array[Any], /, *, offset: int = ..., dtype: DTypeLike | None = ...) -> Array[Any]: ...
linalg: _Linalg
class _FFT:
    @staticmethod
    def fft(x: Array[Any], /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def ifft(x: Array[Any], /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def rfft(x: Array[Any], /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def irfft(x: Array[Any], /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def hfft(x: Array[Any], /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def ihfft(x: Array[Any], /, *, n: int | None = ..., axis: int = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def fftn(x: Array[Any], /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def ifftn(x: Array[Any], /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def fft2(x: Array[Any], /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def ifft2(x: Array[Any], /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def rfftn(x: Array[Any], /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def irfftn(x: Array[Any], /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def rfft2(x: Array[Any], /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def irfft2(x: Array[Any], /, *, s: tuple[int, ...] | None = ..., axes: tuple[int, ...] | None = ..., norm: Literal["backward", "forward", "ortho"] | None = ...) -> Array[Any]: ...
    @staticmethod
    def fftfreq(n: int, /, *, d: float = ..., dtype: DTypeLike | None = ..., device: _Device = ...) -> Array[Any]: ...
    @staticmethod
    def rfftfreq(n: int, /, *, d: float = ..., dtype: DTypeLike | None = ..., device: _Device = ...) -> Array[Any]: ...
    @staticmethod
    def fftshift(x: Array[Any], /, *, axes: _Axis = ...) -> Array[Any]: ...
    @staticmethod
    def ifftshift(x: Array[Any], /, *, axes: _Axis = ...) -> Array[Any]: ...
fft: _FFT
class _NamespaceInfo:
    def capabilities(self) -> dict[str, object]: ...
    def devices(self) -> tuple[str, ...]: ...
    def default_device(self) -> str: ...
    def default_dtypes(self, *, device: _Device = ...) -> dict[str, DTypeLike]: ...
    def dtypes(self, *, device: _Device = ..., kind: str | tuple[str, ...] | None = ...) -> dict[str, DTypeLike]: ...
def __array_namespace_info__() -> _NamespaceInfo: ...
