from collections.abc import Iterable, Iterator, Sequence
from typing import Any, Literal, SupportsIndex, overload
import numpy as np
from numpy.typing import NDArray, DTypeLike

_Layout = Literal["packed", "word-aligned"]
_Bits = Literal[1, 2, 3, 4, 5, 6, 7, 8]

class Array:
    def __init__(self, values: Iterable[SupportsIndex], *, bits: _Bits = ..., layout: _Layout = ...) -> None: ...
    @property
    def bits(self) -> int: ...
    @property
    def layout(self) -> _Layout: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def shape(self) -> tuple[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def dtype(self) -> np.dtype[np.uint8]: ...
    def __array__(self, dtype: DTypeLike | None = ..., copy: bool | None = ...) -> NDArray[Any]: ...
    def __add__(self, other: object) -> NDArray[Any]: ...
    def __radd__(self, other: object) -> NDArray[Any]: ...
    def __sub__(self, other: object) -> NDArray[Any]: ...
    def __rsub__(self, other: object) -> NDArray[Any]: ...
    def __mul__(self, other: object) -> NDArray[Any]: ...
    def __rmul__(self, other: object) -> NDArray[Any]: ...
    def __truediv__(self, other: object) -> NDArray[Any]: ...
    def __rtruediv__(self, other: object) -> NDArray[Any]: ...
    def __floordiv__(self, other: object) -> NDArray[Any]: ...
    def __rfloordiv__(self, other: object) -> NDArray[Any]: ...
    def __mod__(self, other: object) -> NDArray[Any]: ...
    def __rmod__(self, other: object) -> NDArray[Any]: ...
    def __and__(self, other: object) -> NDArray[Any]: ...
    def __rand__(self, other: object) -> NDArray[Any]: ...
    def __or__(self, other: object) -> NDArray[Any]: ...
    def __ror__(self, other: object) -> NDArray[Any]: ...
    def __xor__(self, other: object) -> NDArray[Any]: ...
    def __rxor__(self, other: object) -> NDArray[Any]: ...
    def __lshift__(self, other: object) -> NDArray[Any]: ...
    def __rlshift__(self, other: object) -> NDArray[Any]: ...
    def __rshift__(self, other: object) -> NDArray[Any]: ...
    def __rrshift__(self, other: object) -> NDArray[Any]: ...
    def __eq__(self, other: object) -> NDArray[np.bool_]: ...  # type: ignore[override]
    def __ne__(self, other: object) -> NDArray[np.bool_]: ...  # type: ignore[override]
    def __lt__(self, other: object) -> NDArray[np.bool_]: ...
    def __le__(self, other: object) -> NDArray[np.bool_]: ...
    def __gt__(self, other: object) -> NDArray[np.bool_]: ...
    def __ge__(self, other: object) -> NDArray[np.bool_]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    @overload
    def __getitem__(self, key: SupportsIndex, /) -> int: ...
    @overload
    def __getitem__(self, key: slice, /) -> Array: ...
    def __setitem__(self, key: SupportsIndex, value: SupportsIndex, /) -> None: ...
    def count(self, value: SupportsIndex, /) -> int: ...
    def equals(self, other: object, /) -> bool: ...
    def copy(self) -> Array: ...
    def tobytes(self) -> bytes: ...
    def tolist(self) -> list[int]: ...
    @property
    def base(self) -> Array | None: ...
    def sum(self) -> int: ...
    def find(self, needle: Iterable[SupportsIndex], /) -> int: ...
    def gather(self, indices: Iterable[SupportsIndex], /) -> Array: ...

class Matrix:
    def __init__(self, rows: Iterable[Iterable[SupportsIndex]], *, bits: _Bits = ..., layout: _Layout = ...) -> None: ...
    @classmethod
    def from_flat(cls, values: Iterable[SupportsIndex], shape: tuple[SupportsIndex, SupportsIndex], *, bits: _Bits = ..., layout: _Layout = ...) -> Matrix: ...
    @property
    def bits(self) -> int: ...
    @property
    def layout(self) -> _Layout: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def dtype(self) -> np.dtype[np.uint8]: ...
    def __array__(self, dtype: DTypeLike | None = ..., copy: bool | None = ...) -> NDArray[Any]: ...
    def __add__(self, other: object) -> NDArray[Any]: ...
    def __radd__(self, other: object) -> NDArray[Any]: ...
    def __sub__(self, other: object) -> NDArray[Any]: ...
    def __rsub__(self, other: object) -> NDArray[Any]: ...
    def __mul__(self, other: object) -> NDArray[Any]: ...
    def __rmul__(self, other: object) -> NDArray[Any]: ...
    def __truediv__(self, other: object) -> NDArray[Any]: ...
    def __rtruediv__(self, other: object) -> NDArray[Any]: ...
    def __floordiv__(self, other: object) -> NDArray[Any]: ...
    def __rfloordiv__(self, other: object) -> NDArray[Any]: ...
    def __mod__(self, other: object) -> NDArray[Any]: ...
    def __rmod__(self, other: object) -> NDArray[Any]: ...
    def __and__(self, other: object) -> NDArray[Any]: ...
    def __rand__(self, other: object) -> NDArray[Any]: ...
    def __or__(self, other: object) -> NDArray[Any]: ...
    def __ror__(self, other: object) -> NDArray[Any]: ...
    def __xor__(self, other: object) -> NDArray[Any]: ...
    def __rxor__(self, other: object) -> NDArray[Any]: ...
    def __lshift__(self, other: object) -> NDArray[Any]: ...
    def __rlshift__(self, other: object) -> NDArray[Any]: ...
    def __rshift__(self, other: object) -> NDArray[Any]: ...
    def __rrshift__(self, other: object) -> NDArray[Any]: ...
    def __eq__(self, other: object) -> NDArray[np.bool_]: ...  # type: ignore[override]
    def __ne__(self, other: object) -> NDArray[np.bool_]: ...  # type: ignore[override]
    def __lt__(self, other: object) -> NDArray[np.bool_]: ...
    def __le__(self, other: object) -> NDArray[np.bool_]: ...
    def __gt__(self, other: object) -> NDArray[np.bool_]: ...
    def __ge__(self, other: object) -> NDArray[np.bool_]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Array]: ...
    @overload
    def __getitem__(self, key: SupportsIndex, /) -> Array: ...
    @overload
    def __getitem__(self, key: slice, /) -> Matrix: ...
    @overload
    def __getitem__(self, key: tuple[SupportsIndex, SupportsIndex], /) -> int: ...
    def __setitem__(self, key: tuple[SupportsIndex, SupportsIndex], value: SupportsIndex, /) -> None: ...
    def count(self, value: SupportsIndex, /) -> int: ...
    def equals(self, other: object, /) -> bool: ...
    def copy(self) -> Matrix: ...
    def tobytes(self) -> bytes: ...
    def tolist(self) -> list[list[int]]: ...

class RaggedArray:
    def __init__(self, rows: Iterable[Iterable[SupportsIndex]], *, bits: _Bits = ..., layout: _Layout = ...) -> None: ...
    @classmethod
    def from_flat(cls, values: Iterable[SupportsIndex], offsets: Iterable[SupportsIndex], *, bits: _Bits = ..., layout: _Layout = ...) -> RaggedArray: ...
    @property
    def bits(self) -> int: ...
    @property
    def layout(self) -> _Layout: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def shape(self) -> tuple[int, None]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Array]: ...
    @overload
    def __getitem__(self, key: SupportsIndex, /) -> Array: ...
    @overload
    def __getitem__(self, key: slice, /) -> RaggedArray: ...
    @overload
    def __getitem__(self, key: tuple[SupportsIndex, SupportsIndex], /) -> int: ...
    def __setitem__(self, key: tuple[SupportsIndex, SupportsIndex], value: SupportsIndex, /) -> None: ...
    def count(self, value: SupportsIndex, /) -> int: ...
    def equals(self, other: object, /) -> bool: ...
    def copy(self) -> RaggedArray: ...
    def tobytes(self) -> bytes: ...
    def tolist(self) -> list[list[int]]: ...

__all__ = ["Array", "Matrix", "RaggedArray"]
