from collections.abc import Iterable, Iterator, Sequence
from typing import Literal, SupportsIndex, overload, TypeVar
import numpy as np
_Scalar = np.bool_ | np.uint8 | np.uint16 | np.uint32 | np.uint64 | np.int8 | np.int16 | np.int32 | np.int64 | np.float32 | np.float64 | np.complex64 | np.complex128
_NDArray = np.ndarray[tuple[int, ...], np.dtype[_Scalar]]
_DTypeLike = str | type[_Scalar] | np.dtype[_Scalar]

_DType = TypeVar("_DType", bound=_Scalar)

_Layout = Literal["packed", "word-aligned"]
_Bits = Literal[1, 2, 3, 4, 5, 6, 7, 8]

class Array:
    def __init__(self, values: Iterable[SupportsIndex], *, bits: _Bits = ..., layout: _Layout = ...) -> None: ...
    @property
    def bits(self) -> int: ...
    @property
    def layout(self) -> _Layout: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def shape(self) -> tuple[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def dtype(self) -> np.dtype[np.uint8]: ...
    @overload
    def __array__(self, dtype: None = ..., copy: bool | None = ...) -> np.ndarray[tuple[int, ...], np.dtype[np.uint8]]: ...
    @overload
    def __array__(self, dtype: type[_DType] | np.dtype[_DType], copy: bool | None = ...) -> np.ndarray[tuple[int, ...], np.dtype[_DType]]: ...
    @overload
    def __array__(self, dtype: _DTypeLike | None = ..., copy: bool | None = ...) -> _NDArray: ...
    def __add__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __radd__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __sub__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rsub__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __mul__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rmul__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __truediv__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rtruediv__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __floordiv__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rfloordiv__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __mod__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rmod__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __and__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rand__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __or__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __ror__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __xor__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rxor__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __lshift__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rlshift__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rshift__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rrshift__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __eq__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...  # type: ignore[override]
    def __ne__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...  # type: ignore[override]
    def __lt__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...
    def __le__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...
    def __gt__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...
    def __ge__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    @overload
    def __getitem__(self, key: SupportsIndex, /) -> int: ...
    @overload
    def __getitem__(self, key: slice, /) -> Array: ...
    def __setitem__(self, key: SupportsIndex, value: SupportsIndex, /) -> None: ...
    def count(self, value: SupportsIndex, /) -> int: ...
    def equals(self, other: object, /) -> bool: ...
    def copy(self) -> Array: ...
    def tobytes(self) -> bytes: ...
    def tolist(self) -> list[int]: ...
    @property
    def base(self) -> Array | None: ...
    def sum(self) -> int: ...
    def find(self, needle: Iterable[SupportsIndex], /) -> int: ...
    def gather(self, indices: Iterable[SupportsIndex], /) -> Array: ...

class Matrix:
    def __init__(self, rows: Iterable[Iterable[SupportsIndex]], *, bits: _Bits = ..., layout: _Layout = ...) -> None: ...
    @classmethod
    def from_flat(cls, values: Iterable[SupportsIndex], shape: tuple[SupportsIndex, SupportsIndex], *, bits: _Bits = ..., layout: _Layout = ...) -> Matrix: ...
    @property
    def bits(self) -> int: ...
    @property
    def layout(self) -> _Layout: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def dtype(self) -> np.dtype[np.uint8]: ...
    @overload
    def __array__(self, dtype: None = ..., copy: bool | None = ...) -> np.ndarray[tuple[int, ...], np.dtype[np.uint8]]: ...
    @overload
    def __array__(self, dtype: type[_DType] | np.dtype[_DType], copy: bool | None = ...) -> np.ndarray[tuple[int, ...], np.dtype[_DType]]: ...
    @overload
    def __array__(self, dtype: _DTypeLike | None = ..., copy: bool | None = ...) -> _NDArray: ...
    def __add__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __radd__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __sub__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rsub__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __mul__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rmul__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __truediv__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rtruediv__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __floordiv__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rfloordiv__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __mod__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rmod__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __and__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rand__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __or__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __ror__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __xor__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rxor__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __lshift__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rlshift__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rshift__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __rrshift__(self, other: Array | Matrix | _NDArray | int | float | complex) -> _NDArray: ...
    def __eq__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...  # type: ignore[override]
    def __ne__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...  # type: ignore[override]
    def __lt__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...
    def __le__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...
    def __gt__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...
    def __ge__(self, other: object) -> np.ndarray[tuple[int, ...], np.dtype[np.bool_]]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Array]: ...
    @overload
    def __getitem__(self, key: SupportsIndex, /) -> Array: ...
    @overload
    def __getitem__(self, key: slice, /) -> Matrix: ...
    @overload
    def __getitem__(self, key: tuple[SupportsIndex, SupportsIndex], /) -> int: ...
    def __setitem__(self, key: tuple[SupportsIndex, SupportsIndex], value: SupportsIndex, /) -> None: ...
    def count(self, value: SupportsIndex, /) -> int: ...
    def equals(self, other: object, /) -> bool: ...
    def copy(self) -> Matrix: ...
    def tobytes(self) -> bytes: ...
    def tolist(self) -> list[list[int]]: ...

class RaggedArray:
    def __init__(self, rows: Iterable[Iterable[SupportsIndex]], *, bits: _Bits = ..., layout: _Layout = ...) -> None: ...
    @classmethod
    def from_flat(cls, values: Iterable[SupportsIndex], offsets: Iterable[SupportsIndex], *, bits: _Bits = ..., layout: _Layout = ...) -> RaggedArray: ...
    @property
    def bits(self) -> int: ...
    @property
    def layout(self) -> _Layout: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def shape(self) -> tuple[int, None]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Array]: ...
    @overload
    def __getitem__(self, key: SupportsIndex, /) -> Array: ...
    @overload
    def __getitem__(self, key: slice, /) -> RaggedArray: ...
    @overload
    def __getitem__(self, key: tuple[SupportsIndex, SupportsIndex], /) -> int: ...
    def __setitem__(self, key: tuple[SupportsIndex, SupportsIndex], value: SupportsIndex, /) -> None: ...
    def count(self, value: SupportsIndex, /) -> int: ...
    def equals(self, other: object, /) -> bool: ...
    def copy(self) -> RaggedArray: ...
    def tobytes(self) -> bytes: ...
    def tolist(self) -> list[list[int]]: ...

__all__ = ["Array", "Matrix", "RaggedArray"]
